// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A Power BI user access right entry for capacity
    /// </summary>
    public partial class CapacityUser : User
    {
        /// <summary>
        /// Initializes a new instance of the CapacityUser class.
        /// </summary>
        public CapacityUser()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CapacityUser class.
        /// </summary>
        /// <param name="emailAddress">Email address of the user</param>
        /// <param name="identifier">Identifier of the principal</param>
        /// <param name="principalType">Possible values include: 'None',
        /// 'User', 'Group', 'App'</param>
        /// <param name="capacityUserAccessRight">Access right user has on the
        /// capacity. Possible values include: 'None', 'Assign',
        /// 'Admin'</param>
        /// <param name="displayName">Display name of the principal</param>
        /// <param name="graphId">Identifier of the principal in Microsoft
        /// Graph. Only available for admin APIs.</param>
        public CapacityUser(string emailAddress, string identifier, PrincipalType principalType, CapacityUserAccessRight capacityUserAccessRight, string displayName = default(string), string graphId = default(string))
            : base(emailAddress, identifier, principalType, displayName, graphId)
        {
            CapacityUserAccessRight = capacityUserAccessRight;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets access right user has on the capacity. Possible values
        /// include: 'None', 'Assign', 'Admin'
        /// </summary>
        [JsonProperty(PropertyName = "capacityUserAccessRight")]
        public CapacityUserAccessRight CapacityUserAccessRight { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
