// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for CapacityUserAccessRight.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(CapacityUserAccessRightConverter))]
    public struct CapacityUserAccessRight : System.IEquatable<CapacityUserAccessRight>
    {
        private CapacityUserAccessRight(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        /// <summary>
        /// User doesn't have access to the capacity
        /// </summary>
        public static readonly CapacityUserAccessRight None = "None";

        /// <summary>
        /// User has contributor rights and can assign workspaces to the
        /// capacity
        /// </summary>
        public static readonly CapacityUserAccessRight Assign = "Assign";

        /// <summary>
        /// User has administrator rights on the capacity
        /// </summary>
        public static readonly CapacityUserAccessRight Admin = "Admin";


        /// <summary>
        /// Underlying value of enum CapacityUserAccessRight
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for CapacityUserAccessRight
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type CapacityUserAccessRight
        /// </summary>
        public bool Equals(CapacityUserAccessRight e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to CapacityUserAccessRight
        /// </summary>
        public static implicit operator CapacityUserAccessRight(string value)
        {
            return new CapacityUserAccessRight(value);
        }

        /// <summary>
        /// Implicit operator to convert CapacityUserAccessRight to string
        /// </summary>
        public static implicit operator string(CapacityUserAccessRight e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum CapacityUserAccessRight
        /// </summary>
        public static bool operator == (CapacityUserAccessRight e1, CapacityUserAccessRight e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum CapacityUserAccessRight
        /// </summary>
        public static bool operator != (CapacityUserAccessRight e1, CapacityUserAccessRight e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for CapacityUserAccessRight
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is CapacityUserAccessRight && Equals((CapacityUserAccessRight)obj);
        }

        /// <summary>
        /// Returns for hashCode CapacityUserAccessRight
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
