// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.PowerBI.Api.V1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// The gateway info
    /// </summary>
    public partial class CreateGatewayRequest
    {
        /// <summary>
        /// Initializes a new instance of the CreateGatewayRequest class.
        /// </summary>
        public CreateGatewayRequest() { }

        /// <summary>
        /// Initializes a new instance of the CreateGatewayRequest class.
        /// </summary>
        public CreateGatewayRequest(string name = default(string), string publicKey = default(string), string annotation = default(string), IList<WorkspaceId> workspaces = default(IList<WorkspaceId>))
        {
            Name = name;
            PublicKey = publicKey;
            Annotation = annotation;
            Workspaces = workspaces;
        }

        /// <summary>
        /// The gateway name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// The gateway public key
        /// </summary>
        [JsonProperty(PropertyName = "publicKey")]
        public string PublicKey { get; set; }

        /// <summary>
        /// The gateway annotation
        /// </summary>
        [JsonProperty(PropertyName = "annotation")]
        public string Annotation { get; set; }

        /// <summary>
        /// The workspace id to add the gateway to
        /// </summary>
        [JsonProperty(PropertyName = "workspaces")]
        public IList<WorkspaceId> Workspaces { get; set; }

    }
}
