// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A list of miscellaneous properties returned for a dataset. Returned by
    /// User and Admin APIs.
    /// </summary>
    public partial class DatasetMiscProperties
    {
        /// <summary>
        /// Initializes a new instance of the DatasetMiscProperties class.
        /// </summary>
        public DatasetMiscProperties()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DatasetMiscProperties class.
        /// </summary>
        /// <param name="addRowsAPIEnabled">Whether the dataset allows adding
        /// new rows</param>
        /// <param name="isRefreshable">Whether the dataset is refreshable or
        /// not. A Power BI refreshable dataset is a dataset that has been
        /// refreshed at least once, or for which a valid refresh schedule
        /// exists.</param>
        /// <param name="isInPlaceSharingEnabled">Whether the dataset can be
        /// shared with external users to be consumed in their own
        /// tenant</param>
        public DatasetMiscProperties(bool? addRowsAPIEnabled = default(bool?), bool? isRefreshable = default(bool?), bool? isInPlaceSharingEnabled = default(bool?))
        {
            AddRowsAPIEnabled = addRowsAPIEnabled;
            IsRefreshable = isRefreshable;
            IsInPlaceSharingEnabled = isInPlaceSharingEnabled;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets whether the dataset allows adding new rows
        /// </summary>
        [JsonProperty(PropertyName = "addRowsAPIEnabled")]
        public bool? AddRowsAPIEnabled { get; set; }

        /// <summary>
        /// Gets or sets whether the dataset is refreshable or not. A Power BI
        /// refreshable dataset is a dataset that has been refreshed at least
        /// once, or for which a valid refresh schedule exists.
        /// </summary>
        [JsonProperty(PropertyName = "IsRefreshable")]
        public bool? IsRefreshable { get; set; }

        /// <summary>
        /// Gets or sets whether the dataset can be shared with external users
        /// to be consumed in their own tenant
        /// </summary>
        [JsonProperty(PropertyName = "IsInPlaceSharingEnabled")]
        public bool? IsInPlaceSharingEnabled { get; set; }

    }
}
