// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The OData response wrapper for a list of Power BI users with access to
    /// a dataflow
    /// </summary>
    public partial class DataflowUsers
    {
        /// <summary>
        /// Initializes a new instance of the DataflowUsers class.
        /// </summary>
        public DataflowUsers()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DataflowUsers class.
        /// </summary>
        /// <param name="value">The list of users with access to a
        /// dataflow</param>
        public DataflowUsers(string odatacontext = default(string), IList<DataflowUser> value = default(IList<DataflowUser>))
        {
            Odatacontext = odatacontext;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "odata.context")]
        public string Odatacontext { get; set; }

        /// <summary>
        /// Gets or sets the list of users with access to a dataflow
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<DataflowUser> Value { get; set; }

    }
}
