// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Power BI dataset refresh target
    /// </summary>
    public partial class DatasetRefreshObjects
    {
        /// <summary>
        /// Initializes a new instance of the DatasetRefreshObjects class.
        /// </summary>
        public DatasetRefreshObjects()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DatasetRefreshObjects class.
        /// </summary>
        /// <param name="table">Table to refresh</param>
        /// <param name="partition">Partition to refresh</param>
        public DatasetRefreshObjects(string table = default(string), string partition = default(string))
        {
            Table = table;
            Partition = partition;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets table to refresh
        /// </summary>
        [JsonProperty(PropertyName = "table")]
        public string Table { get; set; }

        /// <summary>
        /// Gets or sets partition to refresh
        /// </summary>
        [JsonProperty(PropertyName = "partition")]
        public string Partition { get; set; }

    }
}
