// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Response of a data set execute queries request.
    /// </summary>
    public partial class DatasetExecuteQueriesResponse
    {
        /// <summary>
        /// Initializes a new instance of the DatasetExecuteQueriesResponse
        /// class.
        /// </summary>
        public DatasetExecuteQueriesResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DatasetExecuteQueriesResponse
        /// class.
        /// </summary>
        /// <param name="results">A list of results, one per input
        /// query.</param>
        public DatasetExecuteQueriesResponse(IList<DatasetExecuteQueriesQueryResult> results = default(IList<DatasetExecuteQueriesQueryResult>))
        {
            Results = results;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a list of results, one per input query.
        /// </summary>
        [JsonProperty(PropertyName = "results")]
        public IList<DatasetExecuteQueriesQueryResult> Results { get; set; }

    }
}
