// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DatamartDatasourceUsagesProperties
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DatamartDatasourceUsagesProperties class.
        /// </summary>
        public DatamartDatasourceUsagesProperties()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// DatamartDatasourceUsagesProperties class.
        /// </summary>
        /// <param name="datasourceUsages">The data source usages</param>
        public DatamartDatasourceUsagesProperties(IList<DatasourceUsage> datasourceUsages = default(IList<DatasourceUsage>))
        {
            DatasourceUsages = datasourceUsages;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the data source usages
        /// </summary>
        [JsonProperty(PropertyName = "datasourceUsages")]
        public IList<DatasourceUsage> DatasourceUsages { get; set; }

    }
}
