// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The deployment execution step
    /// </summary>
    public partial class DeploymentExecutionStep
    {
        /// <summary>
        /// Initializes a new instance of the DeploymentExecutionStep class.
        /// </summary>
        public DeploymentExecutionStep()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeploymentExecutionStep class.
        /// </summary>
        /// <param name="index">The step index</param>
        /// <param name="type">The deployment step type. Possible values
        /// include: 'DatasetDeployment', 'ReportDeployment',
        /// 'DashboardDeployment'</param>
        /// <param name="status">The status of the pipeline operation. Possible
        /// values include: 'NotStarted', 'Executing', 'Succeeded',
        /// 'Failed'</param>
        /// <param name="sourceAndTarget">The source and target items of the
        /// step</param>
        /// <param name="error">Error details of the step's failure</param>
        public DeploymentExecutionStep(int index, DeploymentStepType type, PipelineOperationStatus status, DeploymentSourceAndTarget sourceAndTarget = default(DeploymentSourceAndTarget), DeploymentError error = default(DeploymentError))
        {
            Index = index;
            Type = type;
            Status = status;
            SourceAndTarget = sourceAndTarget;
            Error = error;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the step index
        /// </summary>
        [JsonProperty(PropertyName = "index")]
        public int Index { get; set; }

        /// <summary>
        /// Gets or sets the deployment step type. Possible values include:
        /// 'DatasetDeployment', 'ReportDeployment', 'DashboardDeployment'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public DeploymentStepType Type { get; set; }

        /// <summary>
        /// Gets or sets the status of the pipeline operation. Possible values
        /// include: 'NotStarted', 'Executing', 'Succeeded', 'Failed'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public PipelineOperationStatus Status { get; set; }

        /// <summary>
        /// Gets or sets the source and target items of the step
        /// </summary>
        [JsonProperty(PropertyName = "sourceAndTarget")]
        public DeploymentSourceAndTarget SourceAndTarget { get; set; }

        /// <summary>
        /// Gets or sets error details of the step's failure
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public DeploymentError Error { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (SourceAndTarget != null)
            {
                SourceAndTarget.Validate();
            }
        }
    }
}
