// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The request data to be used when defining or reporting rules for a
    /// Power BI goal status
    /// </summary>
    public partial class GoalsRulesGoalStatusRules
    {
        /// <summary>
        /// Initializes a new instance of the GoalsRulesGoalStatusRules class.
        /// </summary>
        public GoalsRulesGoalStatusRules()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GoalsRulesGoalStatusRules class.
        /// </summary>
        /// <param name="rules">The list of rules</param>
        /// <param name="defaultOutput">The status ID when no rule is matching.
        /// 0 - 'Not started', 1 - 'On track', 2 - 'At risk', 3 - 'Behind', 4 -
        /// 'Overdue', 5 - 'Completed' .</param>
        /// <param name="scorecardObjectId">The scorecard ID</param>
        /// <param name="goalObjectId">The goal ID</param>
        /// <param name="lastModifiedTime">The UTC time at last
        /// modification</param>
        public GoalsRulesGoalStatusRules(IList<GoalsRulesRule1OfInt32> rules = default(IList<GoalsRulesRule1OfInt32>), int? defaultOutput = default(int?), string scorecardObjectId = default(string), string goalObjectId = default(string), System.DateTime? lastModifiedTime = default(System.DateTime?))
        {
            Rules = rules;
            DefaultOutput = defaultOutput;
            ScorecardObjectId = scorecardObjectId;
            GoalObjectId = goalObjectId;
            LastModifiedTime = lastModifiedTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the list of rules
        /// </summary>
        [JsonProperty(PropertyName = "rules")]
        public IList<GoalsRulesRule1OfInt32> Rules { get; set; }

        /// <summary>
        /// Gets or sets the status ID when no rule is matching. 0 - 'Not
        /// started', 1 - 'On track', 2 - 'At risk', 3 - 'Behind', 4 -
        /// 'Overdue', 5 - 'Completed' .
        /// </summary>
        [JsonProperty(PropertyName = "defaultOutput")]
        public int? DefaultOutput { get; set; }

        /// <summary>
        /// Gets or sets the scorecard ID
        /// </summary>
        [JsonProperty(PropertyName = "scorecardObjectId")]
        public string ScorecardObjectId { get; set; }

        /// <summary>
        /// Gets or sets the goal ID
        /// </summary>
        [JsonProperty(PropertyName = "goalObjectId")]
        public string GoalObjectId { get; set; }

        /// <summary>
        /// Gets or sets the UTC time at last modification
        /// </summary>
        [JsonProperty(PropertyName = "lastModifiedTime")]
        public System.DateTime? LastModifiedTime { get; set; }

    }
}
