// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Preview feature: A blob to specify identity for EmbedToken generation.
    /// Only supported for datasets with Direct Query connection to SQL Azure
    /// </summary>
    public partial class IdentityBlob
    {
        /// <summary>
        /// Initializes a new instance of the IdentityBlob class.
        /// </summary>
        public IdentityBlob()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IdentityBlob class.
        /// </summary>
        /// <param name="value">OAuth2 access token for SQL Azure</param>
        public IdentityBlob(string value)
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets oAuth2 access token for SQL Azure
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Value == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Value");
            }
        }
    }
}
