// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Composite of artifact IDs and label change status.
    /// </summary>
    public partial class InformationProtectionChangeLabelResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// InformationProtectionChangeLabelResponse class.
        /// </summary>
        public InformationProtectionChangeLabelResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// InformationProtectionChangeLabelResponse class.
        /// </summary>
        /// <param name="dashboards">List of unique dashboard IDs with label
        /// change status.</param>
        /// <param name="reports">List of unique report IDs with label change
        /// status.</param>
        /// <param name="dataflows">List of unique dataflow IDs with label
        /// change status.</param>
        /// <param name="datasets">List of unique dataset IDs with label change
        /// status.</param>
        public InformationProtectionChangeLabelResponse(IList<ChangeLabelStatus> dashboards = default(IList<ChangeLabelStatus>), IList<ChangeLabelStatus> reports = default(IList<ChangeLabelStatus>), IList<ChangeLabelStatus> dataflows = default(IList<ChangeLabelStatus>), IList<ChangeLabelStatus> datasets = default(IList<ChangeLabelStatus>))
        {
            Dashboards = dashboards;
            Reports = reports;
            Dataflows = dataflows;
            Datasets = datasets;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets list of unique dashboard IDs with label change status.
        /// </summary>
        [JsonProperty(PropertyName = "dashboards")]
        public IList<ChangeLabelStatus> Dashboards { get; set; }

        /// <summary>
        /// Gets or sets list of unique report IDs with label change status.
        /// </summary>
        [JsonProperty(PropertyName = "reports")]
        public IList<ChangeLabelStatus> Reports { get; set; }

        /// <summary>
        /// Gets or sets list of unique dataflow IDs with label change status.
        /// </summary>
        [JsonProperty(PropertyName = "dataflows")]
        public IList<ChangeLabelStatus> Dataflows { get; set; }

        /// <summary>
        /// Gets or sets list of unique dataset IDs with label change status.
        /// </summary>
        [JsonProperty(PropertyName = "datasets")]
        public IList<ChangeLabelStatus> Datasets { get; set; }

    }
}
