// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.PowerBI.Api.V1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Odata response wrapper for a Power BI Workspace list
    /// </summary>
    public partial class ODataResponseListWorkspace
    {
        /// <summary>
        /// Initializes a new instance of the ODataResponseListWorkspace class.
        /// </summary>
        public ODataResponseListWorkspace() { }

        /// <summary>
        /// Initializes a new instance of the ODataResponseListWorkspace class.
        /// </summary>
        public ODataResponseListWorkspace(string odatacontext = default(string), IList<Workspace> value = default(IList<Workspace>))
        {
            Odatacontext = odatacontext;
            Value = value;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "odata.context")]
        public string Odatacontext { get; set; }

        /// <summary>
        /// The workspaces
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<Workspace> Value { get; set; }

    }
}
