// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.PowerBI.Api.V1.Models
{
    using System.Linq;

    /// <summary>
    /// Odata response wrapper for a Power BI Workspace list
    /// </summary>
    public partial class ODataResponseListWorkspace
    {
        /// <summary>
        /// Initializes a new instance of the ODataResponseListWorkspace class.
        /// </summary>
        public ODataResponseListWorkspace() { }

        /// <summary>
        /// Initializes a new instance of the ODataResponseListWorkspace class.
        /// </summary>
        /// <param name="value">The workspaces</param>
        public ODataResponseListWorkspace(string odatacontext = default(string), System.Collections.Generic.IList<Workspace> value = default(System.Collections.Generic.IList<Workspace>))
        {
            Odatacontext = odatacontext;
            Value = value;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "odata.context")]
        public string Odatacontext { get; set; }

        /// <summary>
        /// Gets or sets the workspaces
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "value")]
        public System.Collections.Generic.IList<Workspace> Value { get; set; }

    }
}
