// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A Power BI user access right entry for a deployment pipeline
    /// </summary>
    public partial class PipelineUser
    {
        /// <summary>
        /// Initializes a new instance of the PipelineUser class.
        /// </summary>
        public PipelineUser()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PipelineUser class.
        /// </summary>
        /// <param name="identifier">For the service principal type `User`,
        /// enter *UPN*. Otherwise provide the [object
        /// ID](/power-bi/developer/embedded/embedded-troubleshoot#what-is-the-difference-between-application-object-id-and-principal-object-id)
        /// of the service principal.</param>
        /// <param name="principalType">Possible values include: 'None',
        /// 'User', 'Group', 'App'</param>
        /// <param name="accessRight">(**Required**) The access right a user
        /// has for the deployment pipeline. Possible values include:
        /// 'Admin'</param>
        public PipelineUser(string identifier, PrincipalType principalType, PipelineUserAccessRight? accessRight = default(PipelineUserAccessRight?))
        {
            AccessRight = accessRight;
            Identifier = identifier;
            PrincipalType = principalType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets (**Required**) The access right a user has for the
        /// deployment pipeline. Possible values include: 'Admin'
        /// </summary>
        [JsonProperty(PropertyName = "accessRight")]
        public PipelineUserAccessRight? AccessRight { get; set; }

        /// <summary>
        /// Gets or sets for the service principal type `User`, enter *UPN*.
        /// Otherwise provide the [object
        /// ID](/power-bi/developer/embedded/embedded-troubleshoot#what-is-the-difference-between-application-object-id-and-principal-object-id)
        /// of the service principal.
        /// </summary>
        [JsonProperty(PropertyName = "identifier")]
        public string Identifier { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'None', 'User', 'Group',
        /// 'App'
        /// </summary>
        [JsonProperty(PropertyName = "principalType")]
        public PrincipalType PrincipalType { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Identifier == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Identifier");
            }
        }
    }
}
