// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PipelineUsersProperties
    {
        /// <summary>
        /// Initializes a new instance of the PipelineUsersProperties class.
        /// </summary>
        public PipelineUsersProperties()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PipelineUsersProperties class.
        /// </summary>
        /// <param name="users">The collection of deployment pipeline users.
        /// Only returned when `$expand` is set to `users` in the
        /// request.</param>
        public PipelineUsersProperties(IList<PipelineUser> users = default(IList<PipelineUser>))
        {
            Users = users;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the collection of deployment pipeline users. Only
        /// returned when `$expand` is set to `users` in the request.
        /// </summary>
        [JsonProperty(PropertyName = "users")]
        public IList<PipelineUser> Users { get; set; }

    }
}
