// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Configuration update org app after deployment
    /// </summary>
    public partial class PipelineUpdateAppSettings
    {
        /// <summary>
        /// Initializes a new instance of the PipelineUpdateAppSettings class.
        /// </summary>
        public PipelineUpdateAppSettings()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PipelineUpdateAppSettings class.
        /// </summary>
        /// <param name="updateAppInTargetWorkspace">Whether to update the app
        /// in the target workspace</param>
        public PipelineUpdateAppSettings(bool? updateAppInTargetWorkspace = default(bool?))
        {
            UpdateAppInTargetWorkspace = updateAppInTargetWorkspace;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets whether to update the app in the target workspace
        /// </summary>
        [JsonProperty(PropertyName = "updateAppInTargetWorkspace")]
        public bool? UpdateAppInTargetWorkspace { get; set; }

    }
}
