// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The connection details for a paginated report data source
    /// </summary>
    public partial class RdlDatasourceConnectionDetails
    {
        /// <summary>
        /// Initializes a new instance of the RdlDatasourceConnectionDetails
        /// class.
        /// </summary>
        public RdlDatasourceConnectionDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RdlDatasourceConnectionDetails
        /// class.
        /// </summary>
        /// <param name="server">The connection server</param>
        /// <param name="database">The connection database</param>
        public RdlDatasourceConnectionDetails(string server = default(string), string database = default(string))
        {
            Server = server;
            Database = database;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the connection server
        /// </summary>
        [JsonProperty(PropertyName = "server")]
        public string Server { get; set; }

        /// <summary>
        /// Gets or sets the connection database
        /// </summary>
        [JsonProperty(PropertyName = "database")]
        public string Database { get; set; }

    }
}
