// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.PowerBI.Api.V1.Models
{
    using System.Linq;

    /// <summary>
    /// A Power BI Report
    /// </summary>
    public partial class Report
    {
        /// <summary>
        /// Initializes a new instance of the Report class.
        /// </summary>
        public Report() { }

        /// <summary>
        /// Initializes a new instance of the Report class.
        /// </summary>
        /// <param name="id">The report id</param>
        /// <param name="name">The report name</param>
        /// <param name="webUrl">The report web url</param>
        /// <param name="embedUrl">The report embed url</param>
        public Report(string id = default(string), string name = default(string), string webUrl = default(string), string embedUrl = default(string))
        {
            Id = id;
            Name = name;
            WebUrl = webUrl;
            EmbedUrl = embedUrl;
        }

        /// <summary>
        /// Gets or sets the report id
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the report name
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the report web url
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "webUrl")]
        public string WebUrl { get; set; }

        /// <summary>
        /// Gets or sets the report embed url
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "embedUrl")]
        public string EmbedUrl { get; set; }

    }
}
