// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A role filter
    /// </summary>
    public partial class RoleTablePermission
    {
        /// <summary>
        /// Initializes a new instance of the RoleTablePermission class.
        /// </summary>
        public RoleTablePermission()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RoleTablePermission class.
        /// </summary>
        /// <param name="name">The name of the table specified in the
        /// filter</param>
        /// <param name="filterExpression">The expression that filters the
        /// table specified in the filter</param>
        public RoleTablePermission(string name, string filterExpression = default(string))
        {
            Name = name;
            FilterExpression = filterExpression;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name of the table specified in the filter
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the expression that filters the table specified in the
        /// filter
        /// </summary>
        [JsonProperty(PropertyName = "filterExpression")]
        public string FilterExpression { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
