// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Encryption key information
    /// </summary>
    public partial class TenantKey
    {
        /// <summary>
        /// Initializes a new instance of the TenantKey class.
        /// </summary>
        public TenantKey()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TenantKey class.
        /// </summary>
        /// <param name="id">The ID of the encryption key</param>
        /// <param name="name">The name of the encryption key</param>
        /// <param name="keyVaultKeyIdentifier">The URI that uniquely specifies
        /// the encryption key in Azure Key Vault</param>
        /// <param name="isDefault">Whether the encryption key is the default
        /// key for the entire tenant. Any newly created capacity inherits the
        /// default key.</param>
        /// <param name="createdAt">The creation time of the encryption
        /// key</param>
        /// <param name="updatedAt">The last update time of the encryption
        /// key</param>
        public TenantKey(System.Guid? id = default(System.Guid?), string name = default(string), string keyVaultKeyIdentifier = default(string), bool? isDefault = default(bool?), System.DateTime? createdAt = default(System.DateTime?), System.DateTime? updatedAt = default(System.DateTime?))
        {
            Id = id;
            Name = name;
            KeyVaultKeyIdentifier = keyVaultKeyIdentifier;
            IsDefault = isDefault;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the ID of the encryption key
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// Gets or sets the name of the encryption key
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the URI that uniquely specifies the encryption key in
        /// Azure Key Vault
        /// </summary>
        [JsonProperty(PropertyName = "keyVaultKeyIdentifier")]
        public string KeyVaultKeyIdentifier { get; set; }

        /// <summary>
        /// Gets or sets whether the encryption key is the default key for the
        /// entire tenant. Any newly created capacity inherits the default key.
        /// </summary>
        [JsonProperty(PropertyName = "isDefault")]
        public bool? IsDefault { get; set; }

        /// <summary>
        /// Gets or sets the creation time of the encryption key
        /// </summary>
        [JsonProperty(PropertyName = "createdAt")]
        public System.DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets the last update time of the encryption key
        /// </summary>
        [JsonProperty(PropertyName = "updatedAt")]
        public System.DateTime? UpdatedAt { get; set; }

    }
}
