// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A request for migrating workspaces to a shared capacity as tenant admin
    /// </summary>
    public partial class UnassignWorkspacesCapacityRequest
    {
        /// <summary>
        /// Initializes a new instance of the UnassignWorkspacesCapacityRequest
        /// class.
        /// </summary>
        public UnassignWorkspacesCapacityRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UnassignWorkspacesCapacityRequest
        /// class.
        /// </summary>
        /// <param name="workspacesToUnassign">The workspaces to migrate to a
        /// shared capacity</param>
        public UnassignWorkspacesCapacityRequest(IList<string> workspacesToUnassign)
        {
            WorkspacesToUnassign = workspacesToUnassign;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the workspaces to migrate to a shared capacity
        /// </summary>
        [JsonProperty(PropertyName = "workspacesToUnassign")]
        public IList<string> WorkspacesToUnassign { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (WorkspacesToUnassign == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "WorkspacesToUnassign");
            }
        }
    }
}
