// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.PowerBI.Api.V1.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// An Update Datasource To Gateway Request
    /// </summary>
    public partial class UpdateDatasourceRequest
    {
        /// <summary>
        /// Initializes a new instance of the UpdateDatasourceRequest class.
        /// </summary>
        public UpdateDatasourceRequest() { }

        /// <summary>
        /// Initializes a new instance of the UpdateDatasourceRequest class.
        /// </summary>
        public UpdateDatasourceRequest(CredentialDetails credentialDetails = default(CredentialDetails))
        {
            CredentialDetails = credentialDetails;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "credentialDetails")]
        public CredentialDetails CredentialDetails { get; set; }

    }
}
