// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A Power BI dashboard returned by WorkspaceInfo APIs. The API returns a subset of the following list of dashboard properties. The subset depends on the API called, caller permissions, and the availability of data in the Power BI database. </summary>
    public partial class WorkspaceInfoDashboard : DashboardBaseProperties
    {
        /// <summary> Initializes a new instance of <see cref="WorkspaceInfoDashboard"/>. </summary>
        /// <param name="id"> The dashboard ID. </param>
        public WorkspaceInfoDashboard(Guid id) : base(id)
        {
            Tiles = new ChangeTrackingList<WorkspaceInfoTile>();
            Users = new ChangeTrackingList<DashboardUser>();
            Tags = new ChangeTrackingList<Guid>();
        }

        /// <summary> Initializes a new instance of <see cref="WorkspaceInfoDashboard"/>. </summary>
        /// <param name="id"> The dashboard ID. </param>
        /// <param name="displayName"> The display name of the dashboard. </param>
        /// <param name="isReadOnly"> Whether the dashboard is read-only. </param>
        /// <param name="appId"> The app ID, returned only if the dashboard belongs to an app. </param>
        /// <param name="dataClassification"> The data classification tag of a Power BI item (such as a report or a dashboard). </param>
        /// <param name="sensitivityLabel"> The sensitivity label. </param>
        /// <param name="tiles"> The tiles that belong to the dashboard. </param>
        /// <param name="users"> (Empty value) The dashboard user access details. This property will be removed from the payload response in an upcoming release. You can retrieve user information on a Power BI dashboard by using the [Get Dashboard Users as Admin](/rest/api/power-bi/admin/dashboards-get-dashboard-users-as-admin) API call, or the [PostWorkspaceInfo](/rest/api/power-bi/admin/workspace-info-post-workspace-info) API call with the `getArtifactUsers` parameter. </param>
        /// <param name="tags"> The unique identifiers for the tags applied on an item. </param>
        internal WorkspaceInfoDashboard(Guid id, string displayName, bool? isReadOnly, string appId, string dataClassification, SensitivityLabel sensitivityLabel, IList<WorkspaceInfoTile> tiles, IList<DashboardUser> users, IList<Guid> tags) : base(id, displayName, isReadOnly, appId)
        {
            DataClassification = dataClassification;
            SensitivityLabel = sensitivityLabel;
            Tiles = tiles;
            Users = users;
            Tags = tags;
        }

        /// <summary> The data classification tag of a Power BI item (such as a report or a dashboard). </summary>
        public string DataClassification { get; set; }
        /// <summary> The sensitivity label. </summary>
        public SensitivityLabel SensitivityLabel { get; set; }
        /// <summary> The tiles that belong to the dashboard. </summary>
        public IList<WorkspaceInfoTile> Tiles { get; }
        /// <summary> (Empty value) The dashboard user access details. This property will be removed from the payload response in an upcoming release. You can retrieve user information on a Power BI dashboard by using the [Get Dashboard Users as Admin](/rest/api/power-bi/admin/dashboards-get-dashboard-users-as-admin) API call, or the [PostWorkspaceInfo](/rest/api/power-bi/admin/workspace-info-post-workspace-info) API call with the `getArtifactUsers` parameter. </summary>
        public IList<DashboardUser> Users { get; }
        /// <summary> The unique identifiers for the tags applied on an item. </summary>
        public IList<Guid> Tags { get; }
    }
}
