// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class WorkspaceInfoDashboardTilesProperties
    {
        /// <summary>
        /// Initializes a new instance of the
        /// WorkspaceInfoDashboardTilesProperties class.
        /// </summary>
        public WorkspaceInfoDashboardTilesProperties()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// WorkspaceInfoDashboardTilesProperties class.
        /// </summary>
        /// <param name="tiles">The tiles that belong to the dashboard</param>
        public WorkspaceInfoDashboardTilesProperties(IList<WorkspaceInfoTile> tiles = default(IList<WorkspaceInfoTile>))
        {
            Tiles = tiles;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the tiles that belong to the dashboard
        /// </summary>
        [JsonProperty(PropertyName = "tiles")]
        public IList<WorkspaceInfoTile> Tiles { get; set; }

    }
}
