// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.V2.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Power BI Clone Tile Request
    /// </summary>
    public partial class CloneTileRequest
    {
        /// <summary>
        /// Initializes a new instance of the CloneTileRequest class.
        /// </summary>
        public CloneTileRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CloneTileRequest class.
        /// </summary>
        /// <param name="targetDashboardId">The target dashboard id</param>
        /// <param name="targetWorkspaceId">Optional parameter for specifying
        /// the target workspace id</param>
        /// <param name="targetReportId">Optional parameter for specifying the
        /// target report id</param>
        /// <param name="targetModelId">Optional parameter for specifying the
        /// target associated model (dataset) id</param>
        /// <param name="positionConflictAction">Optional parameter for
        /// specifying the action in case of position conflict</param>
        public CloneTileRequest(string targetDashboardId = default(string), string targetWorkspaceId = default(string), string targetReportId = default(string), string targetModelId = default(string), string positionConflictAction = default(string))
        {
            TargetDashboardId = targetDashboardId;
            TargetWorkspaceId = targetWorkspaceId;
            TargetReportId = targetReportId;
            TargetModelId = targetModelId;
            PositionConflictAction = positionConflictAction;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the target dashboard id
        /// </summary>
        [JsonProperty(PropertyName = "targetDashboardId")]
        public string TargetDashboardId { get; set; }

        /// <summary>
        /// Gets or sets optional parameter for specifying the target workspace
        /// id
        /// </summary>
        [JsonProperty(PropertyName = "targetWorkspaceId")]
        public string TargetWorkspaceId { get; set; }

        /// <summary>
        /// Gets or sets optional parameter for specifying the target report id
        /// </summary>
        [JsonProperty(PropertyName = "targetReportId")]
        public string TargetReportId { get; set; }

        /// <summary>
        /// Gets or sets optional parameter for specifying the target
        /// associated model (dataset) id
        /// </summary>
        [JsonProperty(PropertyName = "targetModelId")]
        public string TargetModelId { get; set; }

        /// <summary>
        /// Gets or sets optional parameter for specifying the action in case
        /// of position conflict
        /// </summary>
        [JsonProperty(PropertyName = "positionConflictAction")]
        public string PositionConflictAction { get; set; }

    }
}
