// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.PowerBI.Api.V2.Models
{
    using Microsoft.PowerBI;
    using Microsoft.PowerBI.Api;
    using Microsoft.PowerBI.Api.V2;

    /// <summary>
    /// Defines values for DatasetMode.
    /// </summary>
    public static class DatasetMode
    {
        public const string AsAzure = "AsAzure";
        public const string AsOnPrem = "AsOnPrem";
        public const string Push = "Push";
        public const string Streaming = "Streaming";
        public const string PushStreaming = "PushStreaming";
    }
}
