// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.V2.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Power BI Create a new group Request
    /// </summary>
    public partial class GroupCreationRequest
    {
        /// <summary>
        /// Initializes a new instance of the GroupCreationRequest class.
        /// </summary>
        public GroupCreationRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GroupCreationRequest class.
        /// </summary>
        /// <param name="name">The name of the new created group.</param>
        public GroupCreationRequest(string name = default(string))
        {
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name of the new created group.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
