// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.V2.Models
{

    /// <summary>
    /// Defines values for StateEnum.
    /// </summary>
    public static class StateEnum
    {
        /// <summary>
        /// Not Supported
        /// </summary>
        public const string NotActivated = "NotActivated";
        /// <summary>
        /// Capacity ready for use
        /// </summary>
        public const string Active = "Active";
        /// <summary>
        /// Capacity in activation process
        /// </summary>
        public const string Provisioning = "Provisioning";
        /// <summary>
        /// Capacity failed to provisioned
        /// </summary>
        public const string ProvisionFailed = "ProvisionFailed";
        /// <summary>
        /// Capacity suspended for use
        /// </summary>
        public const string Suspended = "Suspended";
        /// <summary>
        /// Not Supported
        /// </summary>
        public const string PreSuspended = "PreSuspended";
        /// <summary>
        /// Capacity in process of being deleted
        /// </summary>
        public const string Deleting = "Deleting";
        /// <summary>
        /// Capacity has been deleted and is not available
        /// </summary>
        public const string Deleted = "Deleted";
        /// <summary>
        /// Capacity can not be used
        /// </summary>
        public const string Invalid = "Invalid";
        /// <summary>
        /// Capacity Sku change is in progress
        /// </summary>
        public const string UpdatingSku = "UpdatingSku";
    }
}
