// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api.V2.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Power BI update report content request
    /// </summary>
    public partial class UpdateReportContentRequest
    {
        /// <summary>
        /// Initializes a new instance of the UpdateReportContentRequest class.
        /// </summary>
        public UpdateReportContentRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateReportContentRequest class.
        /// </summary>
        public UpdateReportContentRequest(SourceReport sourceReport)
        {
            SourceReport = sourceReport;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for UpdateReportContentRequest class.
        /// </summary>
        static UpdateReportContentRequest()
        {
            SourceType = "ExistingReport";
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sourceReport")]
        public SourceReport SourceReport { get; set; }

        /// <summary>
        /// The source type for the content update.
        /// </summary>
        [JsonProperty(PropertyName = "sourceType")]
        public static string SourceType { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (SourceReport == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "SourceReport");
            }
            if (SourceReport != null)
            {
                SourceReport.Validate();
            }
        }
    }
}
