// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.PowerBI.Api.V2.Models
{
    using Microsoft.PowerBI;
    using Microsoft.PowerBI.Api;
    using Microsoft.PowerBI.Api.V2;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class UpdateDatasourcesRequest
    {
        /// <summary>
        /// Initializes a new instance of the UpdateDatasourcesRequest class.
        /// </summary>
        public UpdateDatasourcesRequest()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateDatasourcesRequest class.
        /// </summary>
        /// <param name="updateDetails">The connection server</param>
        public UpdateDatasourcesRequest(IList<UpdateDatasourceConnectionRequest> updateDetails = default(IList<UpdateDatasourceConnectionRequest>))
        {
            UpdateDetails = updateDetails;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the connection server
        /// </summary>
        [JsonProperty(PropertyName = "updateDetails")]
        public IList<UpdateDatasourceConnectionRequest> UpdateDetails { get; set; }

    }
}
