// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.PowerBI.Api
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// InformationProtection operations.
    /// </summary>
    public partial interface IInformationProtection
    {
        /// <summary>
        /// Remove sensitivity labels from Power BI items (such as reports or
        /// dashboards) by item ID.
        /// </summary>
        /// <remarks>
        ///
        /// For a usage example, see [Set or remove sensitivity
        /// labels](/power-bi/admin/service-security-sensitivity-label-inheritance-set-remove-api).
        ///
        /// ## Permissions
        ///
        /// - The user must be a Fabric administrator.
        /// - The admin user must have sufficient [usage
        /// rights](/azure/information-protection/configure-usage-rights) to
        /// delete labels.
        ///
        /// ## Required Scope
        ///
        /// Tenant.ReadWrite.All
        ///
        /// ## Limitations
        ///
        /// - Maximum 25 requests per hour.
        /// - Each request can update up to 2,000 Power BI items.
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        /// <param name='artifacts'>
        /// A composite of artifact ID lists for each type
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<InformationProtectionChangeLabelResponse>> RemoveLabelsAsAdminWithHttpMessagesAsync(InformationProtectionArtifactsChangeLabel artifacts, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Set sensitivity labels on Power BI items (such as reports or
        /// dashboards) by item ID.
        /// </summary>
        /// <remarks>
        ///
        /// To set a sensitivity label using this API, the admin user or the
        /// delegated user (if provided) must have the label included in their
        /// [label
        /// policy](/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide).
        /// For a usage example, see [Set or remove sensitivity
        /// labels](/power-bi/admin/service-security-sensitivity-label-inheritance-set-remove-api).
        ///
        /// ## Permissions
        ///
        /// - The user must be a Fabric administrator.
        /// - The admin user and the delegated user (if provided) must have
        /// sufficient [usage
        /// rights](/azure/information-protection/configure-usage-rights) to
        /// set labels.
        ///
        /// ## Required Scope
        ///
        /// Tenant.ReadWrite.All
        ///
        /// ## Limitations
        ///
        /// - Maximum 25 requests per hour.
        /// - Each request can update up to 2,000 Power BI items.
        /// &lt;br&gt;&lt;br&gt;
        /// </remarks>
        /// <param name='informationProtectionChangeLabelDetails'>
        /// Set label details.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<InformationProtectionChangeLabelResponse>> SetLabelsAsAdminWithHttpMessagesAsync(InformationProtectionChangeLabelDetails informationProtectionChangeLabelDetails, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
