// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.PowerBI.Api.V1
{
    using Models;

    /// <summary>
    /// </summary>
    public partial interface IPowerBIClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        Newtonsoft.Json.JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        Newtonsoft.Json.JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        Microsoft.Rest.ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the IDatasets.
        /// </summary>
        IDatasets Datasets { get; }

        /// <summary>
        /// Gets the IGateways.
        /// </summary>
        IGateways Gateways { get; }

        /// <summary>
        /// Gets the IImports.
        /// </summary>
        IImports Imports { get; }

        /// <summary>
        /// Gets the IWorkspaces.
        /// </summary>
        IWorkspaces Workspaces { get; }

        /// <summary>
        /// Gets the IReports.
        /// </summary>
        IReports Reports { get; }

    }
}
